title: comebackerçš„ç”Ÿæ—¥ç‰¹è¾‘
author: Jaden
email: qjddyx@gmail.com
description: >-
    å®å®ç”Ÿæ—¥å¿«ä¹ï¼ä»Šæ—¥å¯¿æ˜Ÿè®°å¾—é¢†å–è›‹ç³•å—·ï¼ğŸ‚
social:
  instagram: jadonqee
  linkedin: ç”²ç›¾-æˆš-79b663108

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
